apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-from-snapshot-provisioned
spec:
  storageClassName: rook-ceph
  dataSource:
    name: snapshot-provisioned
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi