apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapcontent-provisioned
spec:
  deletionPolicy: Delete
  driver: csi.san.synology.com
  source:
    # SSH into Synology NAS and run "synoiscsiwebapi lun list_snapshot" as root. Then provide the "uuid" field as "snapshotHandle".
    snapshotHandle: 5299b327-734e-4838-a889-ac7882874f0e
  volumeSnapshotClassName: synology-retain
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: snapshot-provisioned
    namespace: default
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-provisioned
spec:
  volumeSnapshotClassName: synology-retain
  source:
    volumeSnapshotContentName: snapcontent-provisioned