apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-provisioned
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-provisioned
    namespace: default
  csi:
    driver: csi.san.synology.com
    fsType: btrfs
    # SSH into Synology NAS and run "synoiscsiwebapi lun list" as root. Then provide the "uuid" field as "volumeHandle".
    volumeHandle: d72c9848-18a2-497a-aa6d-9b2363814345
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-iscsi-retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-provisioned
  namespace: default
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: pv-provisioned
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi