apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    storage.mmontes.io/pvc: pvc
spec:
  storageClassName: rook-ceph
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi